bin/subfont, package.json
Includes a fix for the `/` => `/index.<extension>` rename when running off a http url.
=> Update to assetgraph 4

lib/cli.js, package.json
Prereq: https://github.com/assetgraph/assetgraph/pull/899
I thought I'd get subfont to output this summary info instead of calculating it by hand while QAing :)
It could be nice to also include more verbose info for each font variant (maybe grouped by `font-family`) such as the number of glyphs in the subset and the original. I don't think we have the latter available, so it might be something to add after we've implemented the injection of `unicode-range` into the original `@font-face` declarations -- as that will need to extract the list of glyphs in the original.
=> Output a bit of size stats per page

lib/subsetFonts.js
Discovered as part of https://github.com/Munter/subfont/pull/57
I guess we could consider memoizing it inside `subsetFonts`, though, but then the memoized function would have to be handed into a bunch of helper functions. Not sure it's worth it.
=> Don't memoize getFontFaceForFontUsage, it goes bad when running subsetFonts multiple times

lib/subsetFonts.js
I ran into some unhandled rejections with the headless browser, and I think they could occur in a real browser, too.
=> Avoid an unhandled rejection if the font preload polyfill fails for some reason

lib/parseCommandLineOptions.js, lib/subfont.js
There's a bit of evidence that `--recursive` is causing confusion and is hard to control:
* [How do you NOT recursive](https://github.com/Munter/subfont/issues/20)
* [Multiple calls to subfont causing errors](https://github.com/Munter/subfont/issues/26)
We've previously talked about defaulting to non-recursive mode when we do the next major release. I'm leaving this here so we remember :)
=> Make --no-recursive the default

lib/subsetFonts.js, test/subsetFonts.js
It's too sensitive to bundlers, so let's just eat the extra bytes: https://gitter.im/assetgraph/assetgraph?at=5dba0800ef84ab3786c862e3
=> Don't use the short document.fonts.forEach preload polyfill in inlineCss mode

README.md, lib/parseCommandLineOptions.js, lib/subfont.js
I'm switching over from using `subsetFonts` from AssetGraph and I currently use both of these features.
=> Add subsetPerPage & format options

lib/subsetFonts.js
Currently if you inline fonts `subsetFonts` will still try to prefetch the font using Javascript and you end up with:
```
<script>try{new FontFace('FONT__subset','url(data:font/woff2;base64',{'font-weight':'800'}).load()}catch(e){}</script>
```
which just gives network errors.
This PR just ignores JS preloading if we are inlining fonts.
=> Don't attempt to prefetch inlined fonts

lib/subsetFonts.js, test/subfont.js
Fixes https://gitter.im/assetgraph/assetgraph?at=5ece5da89da05a060a3417fc
=> Don't refer to the fallback CSS with an absolute url when inside the canonical root

lib/subsetFonts.js, test/subsetFonts.js, testdata/subsetFonts/unused-variant-preload/index.html
Fixes #92
Addresses the problem discussed here: https://gitter.im/assetgraph/assetgraph?at=5ece6c29a91f120a6cc72bca
Looks like we only weed out the non-subfont-introduced fonts when adding the `<link rel="preload">`s, not the JavaScript-based polyfill.
The `User-Agent` thing I mentioned is a separate problem, since it means that the unused variants copied into the `__subset` font families will end up as .ttfs because they're based on the generic CSS from Google Web Fonts. We could fix that by providing `woff` and `woff2` alternatives as well. Let's discuss and try to address it separately.
This polyfill keeps biting us, maybe the state of web browsers is so that we can remove it soon?
=> Do not preload unused variants in the JavaScript-based polyfill

lib/subfont.js, test/subfont.js
I ran into some small glitches when I tried to run subfont on `https://netlify.com/` because it gets redirected to `https://www.netlify.com/`. This helps a bit -- roughly copied from bringhome.
=> Warn if fetching an entry point results in an HTTP redirect

lib/subsetFonts.js, test/subsetFonts.js
... to prevent Chrome from downloading the fallback font.
https://gitter.im/assetgraph/assetgraph?at=5f01f6e13a0d3931fad4021b
=> Always include the space character U+20 in subsets

lib/unicodeRange.js, test/downloadGoogleFonts.js, test/subsetFonts.js, test/unicodeRange.js
=> Sort the code points numerically before converting to unicode ranges

lib/subsetFonts.js, test/subsetFonts.js
Fixes #31
We can simplify this a lot if/when we let go of the requirement to use Google Web Font's subsetting features. That'll pave the way to run a "self host" step early in the process and share the rest of the code.
=> Self host fallback CSS and fonts for Google Web Fonts

lib/parseCommandLineOptions.js, lib/subfont.js, lib/subsetFonts.js, package.json, test/subfont.js, test/subsetFonts.js, testdata/browserslistInPackageJson/index.html, testdata/browserslistInPackageJson/package.json
Fixes #119
The current set of default browsers happens to result in `woff`+`woff2` and the JS preload polyfill being selected atm., which is luckily the same as our current `--formats` default :tada:
TODO:
=> Use browserslist to configure which font formats to supply subsets and fallbacks in, and whether to add the JS-based preload polyfill

lib/parseCommandLineOptions.js, test/parseCommandLineOptions.js
I was kinda surprised that `subfont --format woff,woff2` didn't work. Turns out yargs doesn't support that even though the option is declared as `array`: https://github.com/yargs/yargs/issues/846
Also, the `array` type is [weird](https://github.com/yargs/yargs/issues/162), so I found that `subfont --formats woff2 path/to/page.html` fails because yargs tries to consume `path/to/page.html` as another format :zany_face:
This PR fixes both issues by switching to `string` and coercing the result into an array.
=> Support subfont --formats foo,bar and fix weirdness with --formats consuming further non-option arguments

lib/subfont.js, package.json, test/subfont.js
Instead of `silent` only controlling whether `logEvents` gets used.
Also, don't break if no console object gets handed in.
I encountered this while writing up https://github.com/Munter/subfont/issues/122#issuecomment-670870698
=> Respect silent:true wrt. the console output

README.md
It is my understanding that v6 of subfont doesn't have any reference to pyftsubset anymore. We should remove the installation instructions for its dependencies
=> Remove installation instructions for fonttools

CHANGELOG.md
It appears that v6.4.2 was added twice when in fact the top most instance is supposed to be v6.5.0.
=> update changelog with proper version for 6.5.0

lib/getFontInfo.js, lib/subsetFonts.js, package.json, test/subfont.js, test/subsetFonts.js
We use `fontkit` for getting the codepoints in a font and information about the variation axes. We can use `harfbuzzjs` for that instead and remove a heavy dependency.
Prerequisite: https://github.com/harfbuzz/harfbuzzjs/pull/77
=> Use harfbuzzjs instead of fontkit

README.md, lib/parseCommandLineOptions.js, lib/subfont.js, lib/subsetFonts.js, test/subsetFonts.js
Makes use of papandreou/subset-font#23
=> Support partial instancing of variable fonts
